# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# you can choose themes from $HOME/.config/kitty/kitty-themes/
#include ./kitty-themes/00-Default.conf
# font_family JetBrainsMono Nerd Font
# bold_font JetBrainsMono Font Bold
# italic_font JetBrainsMono Font Italic
# bold_italic_font JetBrainsMono Font Bold Italic
font_size 16.0

background_opacity 0.9
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
# cursor_trail 1

# hide titlebar
hide_window_decorations no
window_border_width 10
draw_minimal_borders yes

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

foreground #dddddd
background #000000
cursor #dddddd


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' style=Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#

# # ----- Focus panes -----
map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

# ----- Resize panes -----
map alt+shift+h resize_window taller 2
map alt+shift+j resize_window narrower 2
map alt+shift+k resize_window shorter   2
map alt+shift+l resize_window wider     2

# ----- Move panes -----
map alt+ctrl+h move_window left
map alt+ctrl+j move_window down
map alt+ctrl+k move_window up
map alt+ctrl+l move_window right

# ----- Tabs (leave conventional) -----
map alt+tab next_tab
map alt+shift+tab previous_tab
map alt+shift+t new_tab

macos_option_as_alt both

