# ~/.config/starship.toml
add_newline = false
scan_timeout = 20
command_timeout = 300

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$status\
$cmd_duration\
$python\
$line_break\
$character"""

right_format = ""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold purple)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
read_only = " 󰌾"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "
style = "bold yellow"

[git_status]
format = "([$conflicted$renamed$deleted$modified$typechanged$staged$untracked]($style) )"
style = "bold #8a8f98"
conflicted = "[=${count}](bold red) "
renamed = "[»${count}](bold cyan) "
deleted = "[-${count}](bold red) "
modified = "[~${count}](bold yellow) "
typechanged = "[t${count}](bold yellow) "
staged = "[+${count}](bold green) "
untracked = "[?${count}](bold blue) "
ahead = ""
behind = ""
diverged = ""
up_to_date = ""

[git_metrics]
disabled = true

[cmd_duration]
min_time = 1000
format = "[$duration]($style) "
style = "bold yellow"

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "×"
style = "bold red"
map_symbol = false

[python]
symbol = " "
style = "bold yellow"
format = "[(\\($virtualenv\\) )]($style)"

[battery]
disabled = true

[time]
disabled = true

[os]
disabled = true
