# Record *clipboard* (Ctrl+C / "+ register) updates
exec_always wl-paste --watch clipman store --no-persist

# Record *primary selection* (mouse selection / "* register) updates
exec_always wl-paste --primary --watch clipman store --no-persist

# Picker (wofi)
bindsym $mod+Shift+v exec clipman pick -t wofi

