# Rounded corners
# corner_radius 8

# # Shadows
# shadows enable
# # shadows_blur_radius 12
# # shadows_color #00000066

# # Borders look cleaner with transparency
# client.focused          #00000000 #00000000 #ffffff #2e9ef4 #00000000
